.gitignore
docs/UserGuide.md

Adapt the user guide for StudMap from that of AB3 [ Resolve #12 ]
- Add app description for StudMap
- Remove all traces of AB3 from the user guide
- Add entries for the upcoming features

Update user guide 

---

docs/DeveloperGuide.md

The use cases describes the wrong set of use cases.
Let's update the use cases for StudMap instead. 
Resolves #10

Add Use Cases for DG

---

docs/index.md

Index page describes AB3 instead of StudMap.
Let's update it to describe StudMap.

Update Index Page

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/PersonData.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/java/seedu/address/testutil/PersonBuilder.java

- Create parameter object `PersonData` which is used to construct Person. This will allow us to edit the fields in Person and keep the original design pattern of `private final` fields without changing the constructor, since `final` fields must be initialized in the constructor. See: #31 
- Update tests to use this constructor instead.

Create parameter object for Person constructor

---

README.md
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/SortCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

Students are displayed in the order when they were added
There is no simple way to sort the students by name.
TAs who want to sort their students by alphabetical
order could not do so easily.
Let's add a sort command that allows users to sort the student
list by alphabetical order.

Add sort command to sort list by name

---

src/main/java/seedu/address/ui/HelpWindow.java

Let's update the URL for our UG in the help window opened.

Update URL for UG in Help command

---

src/main/java/seedu/address/logic/commands/MarkCommand.java
src/main/java/seedu/address/logic/commands/UnmarkCommand.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/PersonData.java
src/test/java/seedu/address/model/person/PersonTest.java

- Resolve #50 
- Add a method `getPersonData()` in `Person` that reconstructs a `PersonData` from the information stored on `Person`
- Adjust `Mark` and `Unmark` commands to use this
- Note: `EditCommand` is not using this yet; we might need to look more closely
- Add corresponding tests for this method
- Add equals method for `PersonData`

Retrieve PersonData from Person

---

src/main/java/seedu/address/logic/commands/SortCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/SortCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/attribute/Attribute.java
src/main/java/seedu/address/model/attribute/exceptions/AttributeNotFoundException.java
src/main/java/seedu/address/model/order/Order.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/FilterCommandTest.java
src/test/java/seedu/address/logic/commands/SortCommandTest.java

- Let us enhance the sort functionality to support sorting by attributes.
- Resolve #49 
- Modify SortCommand to take in an Attribute and sorting Order specified by user
- Add Attribute and Order class to check for valid attribute and order inputs respectively
- Add test cases for this function

Enhance Sort Command to allow sorting by attributes 

---

docs/DeveloperGuide.md

To-do: update diagrams for AddTag

Update developer guide for AddTag

---

docs/DeveloperGuide.md

- Draft implementation details of `sort`.
- Include design considerations.

Draft for Sort Feature DG

---

src/main/java/seedu/studmap/commons/util/CollectionUtil.java
src/main/java/seedu/studmap/logic/commands/AddTagCommand.java
src/main/java/seedu/studmap/logic/commands/DelTagCommand.java
src/main/java/seedu/studmap/logic/parser/DelTagCommandParser.java
src/main/java/seedu/studmap/logic/parser/StudMapParser.java
src/test/java/seedu/studmap/logic/commands/AddTagCommandTest.java

Implemented using the `EditStudentCommand` system. Resolve #77

Add DelTagCommand to delete tags

---

src/main/java/seedu/studmap/logic/commands/GradeCommand.java
src/main/java/seedu/studmap/logic/commands/MarkCommand.java
src/main/java/seedu/studmap/logic/commands/UngradeCommand.java
src/main/java/seedu/studmap/logic/commands/UnmarkCommand.java
src/main/java/seedu/studmap/logic/parser/GradeCommandParser.java
src/main/java/seedu/studmap/logic/parser/MarkCommandParser.java
src/main/java/seedu/studmap/logic/parser/StudMapParser.java
src/main/java/seedu/studmap/logic/parser/UngradeCommandParser.java
src/main/java/seedu/studmap/logic/parser/UnmarkCommandParser.java
src/test/java/seedu/studmap/logic/commands/UngradeCommandTest.java
src/test/java/seedu/studmap/logic/commands/UnmarkCommandTest.java
src/test/java/seedu/studmap/logic/parser/UngradeCommandParserTest.java
src/test/java/seedu/studmap/logic/parser/UnmarkCommandParserTest.java

Resolve #94 
- Separate assignment from `mark` (`grade`)
- Separate assignment from `unmark` (`ungrade`)
- Split the test class for ungrade as well

Separate assigment from mark

---

src/main/java/seedu/studmap/logic/commands/FilterCommand.java
src/main/java/seedu/studmap/logic/parser/FilterCommandParser.java
src/main/java/seedu/studmap/model/Model.java
src/main/java/seedu/studmap/model/ModelManager.java
src/main/java/seedu/studmap/model/student/AssignmentContainsKeywordsPredicate.java
src/main/java/seedu/studmap/model/student/ModuleContainsKeywordsPredicate.java
src/test/java/seedu/studmap/logic/commands/AddCommandTest.java
src/test/java/seedu/studmap/logic/commands/FilterCommandTest.java

Filter assignments, module and tag

---

README.md
docs/UserGuide.md
src/main/java/seedu/studmap/logic/commands/EditStudentCommand.java

- Update user guide for tag by changing addtag to tag and remove the coming soon part. Resolve #133 
- Update the readme hyperlink to point at the webpage version of UG and DG instead of the github-pages
- Change the generics typecasting for equals() of EditStudentCommand to use wildcard instead of raw type

Update user guide and readme

---

docs/DeveloperGuide.md
docs/UserGuide.md

- Make page titles show up correctly in GitHub pages
- Fix table of contents not appearing in UG and DG

Fix page title and table of contents

---

docs/UserGuide.md
docs/team/lpohsien.md
src/main/java/seedu/studmap/logic/parser/ParserUtil.java
src/main/java/seedu/studmap/model/student/Assignment.java

Add  draft for project portfolio page (PPP) 

---

src/main/java/seedu/studmap/logic/commands/EditCommand.java
src/main/java/seedu/studmap/logic/commands/GradeCommand.java
src/main/java/seedu/studmap/logic/commands/MarkCommand.java
src/main/java/seedu/studmap/logic/commands/ParticipateCommand.java
src/main/java/seedu/studmap/logic/commands/SortCommand.java
src/main/java/seedu/studmap/logic/commands/TagCommand.java
src/main/java/seedu/studmap/logic/commands/UngradeCommand.java
src/main/java/seedu/studmap/logic/commands/UnmarkCommand.java
src/main/java/seedu/studmap/logic/commands/UnparticipateCommand.java
src/main/java/seedu/studmap/logic/commands/UntagCommand.java

Fix error formatting

---

docs/UserGuide.md
src/main/java/seedu/studmap/logic/commands/ParticipateCommand.java
src/main/java/seedu/studmap/logic/commands/UnparticipateCommand.java

- Closes #127, standardizing `PHONE` and `GITNAME`
- Add summary entry for grade and ungrade
- Modify Participate and Unparticipate to match UG better (`COMPONENT`)

Fix UG bugs

---

src/main/java/seedu/studmap/logic/parser/GradeCommandParser.java
src/main/java/seedu/studmap/logic/parser/MarkCommandParser.java
src/main/java/seedu/studmap/logic/parser/ParticipateCommandParser.java

Fix instance where class format error is produced even though there is no class tag.
Closes #146, #124, and also solves similar bug for grade and participate.

Fix Class Format Error

---

src/main/java/seedu/studmap/logic/commands/EditCommand.java
src/main/java/seedu/studmap/logic/commands/EditStudentCommand.java
src/test/java/seedu/studmap/logic/commands/EditCommandTest.java
src/test/java/seedu/studmap/logic/commands/MarkCommandTest.java
src/test/java/seedu/studmap/logic/commands/ParticipateCommandTest.java
src/test/java/seedu/studmap/logic/commands/TagCommandTest.java
src/test/java/seedu/studmap/logic/commands/UngradeCommandTest.java
src/test/java/seedu/studmap/logic/commands/UnmarkCommandTest.java
src/test/java/seedu/studmap/logic/commands/UnparticipateCommandTest.java

Keep view to current student view after EditCommand and EditStudentCommand
Closes #142

Keep View Unchanged

---

src/main/java/seedu/studmap/model/student/Assignment.java
src/main/java/seedu/studmap/storage/JsonAdaptedAssignment.java

- Fix incorrect exception being thrown

Fix assignment crash

---

src/main/java/seedu/studmap/logic/commands/DeleteCommand.java
src/main/java/seedu/studmap/logic/parser/DeleteCommandParser.java
src/main/java/seedu/studmap/logic/parser/ParserUtil.java
src/main/java/seedu/studmap/model/student/Assignment.java
src/main/java/seedu/studmap/model/student/Attendance.java
src/main/java/seedu/studmap/model/student/Participation.java
src/main/java/seedu/studmap/model/student/Student.java
src/test/java/seedu/studmap/logic/commands/DeleteCommandTest.java
src/test/java/seedu/studmap/logic/parser/DeleteCommandParserTest.java
src/test/java/seedu/studmap/logic/parser/StudMapParserTest.java

- Resolves #112 and #143 by ignoring case when checking if participation / attendance / assignment is equal
- Resolves #147 by modifying toString for student

Fix ToString student and Case Sensitivity Issues

---

docs/UserGuide.md
src/main/java/seedu/studmap/model/student/Module.java
src/main/java/seedu/studmap/model/student/Phone.java
src/test/java/seedu/studmap/logic/parser/ParserUtilTest.java
src/test/java/seedu/studmap/model/student/PhoneTest.java
src/test/java/seedu/studmap/storage/JsonAdaptedStudentTest.java

- Resolves #115 by making that case out of scope for StudMap
- Resolves #123 by defining what makes a student unique

Fix phone validation

---

docs/UserGuide.md

Reverts AY2223S1-CS2103T-W13-1/tp#217 to fix formatting issues

Revert "Update UserGuide.md"

---

docs/UserGuide.md

Add CLI Glossary
